version: '2'
services:
  router:
    image: 'armdsplayground/alpine_router:latest'
    stdin_open: true
    tty: true
    networks:
      internal_network:
        ipv4_address: 192.168.2.2
      telnet_network:
        ipv4_address: 192.168.1.2
    cap_add:
      - ALL
  telnet_client:
    image: 'armdsplayground/alpine_bot:latest'
    stdin_open: true
    tty: true
    networks:
      internal_network:
        ipv4_address: 192.168.2.4
    cap_add:
      - NET_ADMIN
  TelnetServer:
    image: 'armdsplayground/alpine_telnet:latest'
    stdin_open: true
    tty: true
    networks:
      telnet_network:
        ipv4_address: 192.168.1.3
    cap_add:
      - ALL
networks:
  telnet_network:
    ipam:
      config:
        - subnet: 192.168.1.1/24
  internal_network:
    ipam:
      config:
        - subnet: 192.168.2.1/24
