version: '2'
services:
  ftp_server:
    image: 'armdsplayground/alpine_ftp:latest'
    stdin_open: true
    tty: true
    networks:
      mySubnet:
        ipv4_address: 193.20.1.4
    cap_add:
      - ALL
  Alice:
    image: 'armdsplayground/alpine_netcat:latest'
    stdin_open: true
    tty: true
    networks:
      mySubnet:
        ipv4_address: 193.20.1.2
  Bob:
    image: 'armdsplayground/alpine_netcat:latest'
    stdin_open: true
    tty: true
    networks:
      mySubnet:
        ipv4_address: 193.20.1.3
  http_server:
    image: 'armdsplayground/lamp:latest'
    stdin_open: true
    tty: true
    networks:
      mySubnet:
        ipv4_address: 193.20.1.5
    volumes:
      - './website:/var/www/'
networks:
  mySubnet:
    ipam:
      config:
        - subnet: 193.20.1.1/24
